### ISSUE TITLE
Integración de dataset latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [covidvenezuela/covid19-venezuela#1]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso sería subir la data diaria para el caso de Venezuela.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:
![image](https://user-images.githubusercontent.com/28235457/77204998-f6332200-6ac1-11ea-8a11-9985d275fead.png)

Lo que necesitaria es subir los números por día de estos lugares:
![image](https://user-images.githubusercontent.com/28235457/77205017-ff23f380-6ac1-11ea-9f15-efc4cada0f93.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_pe

**Comment by covidvenezuela** [comment]
Hola, gracias por escribir.

Por supuesto que puedo ayudarles.

**Comment by ZurMaD** [comment]
@covidvenezuela Gracias por responder, me pondré en contacto luego, estoy esperando respuestas de personas de otros países.

**Comment by ZurMaD** [comment]
Hola @covidvenezuela te daría acceso al repositorio mencionado https://github.com/DataScienceResearchPeru/covid-19_pe para que puedas hacer commits sin problemas o si deseas de otra forma comentame porfavor.

**Comment by covidvenezuela** [comment]
Con el acceso al repositorio es suficiente, usuario es xavieraraque@gmail.com puedes invitarme y dar acceso.

**Comment by ZurMaD** [comment]
> Con el acceso al repositorio es suficiente, usuario es [xavieraraque@gmail.com](mailto:xavieraraque@gmail.com) puedes invitarme y dar acceso.

Listo, te di acceso.
